-- AlterEnum (PostgreSQL: add values to existing enums)
ALTER TYPE "WorkflowStage" ADD VALUE 'IDENTITY_STRATEGY';
ALTER TYPE "WorkflowStage" ADD VALUE 'IDENTITY_ROUTING';

ALTER TYPE "AgentType" ADD VALUE 'IDENTITY_STRATEGIST';
ALTER TYPE "AgentType" ADD VALUE 'IDENTITY_DIRECTOR';

ALTER TYPE "ArtifactType" ADD VALUE 'IDENTITY_STRATEGY';
ALTER TYPE "ArtifactType" ADD VALUE 'IDENTITY_ROUTES_PACK';

-- AlterTable
ALTER TABLE "Brief" ADD COLUMN "identityWorkflowEnabled" BOOLEAN NOT NULL DEFAULT false;
