CREATE TYPE "BriefEngagementType" AS ENUM (
  'CAMPAIGN',
  'BRAND_IDENTITY',
  'CONTENT_SYSTEM',
  'PRODUCT_LAUNCH',
  'ALWAYS_ON_SOCIAL',
  'RETAIL_PROMOTION',
  'EDITORIAL_PRINT',
  'OOH',
  'TVC_FILM',
  'CREATIVE_STRATEGY_ONLY',
  'CUSTOM'
);

ALTER TABLE "Brief" ADD COLUMN "engagementType" "BriefEngagementType" NOT NULL DEFAULT 'CAMPAIGN';
ALTER TABLE "Brief" ADD COLUMN "workstreams" JSONB NOT NULL DEFAULT '[]';
